import { Inter } from "next/font/google";
import "./globals.css";
import FireflyBackground from "../Components/FireflyBackground";
import clsx from "clsx";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Erika A Porath - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground font-inter")}>
        {children}
        <FireflyBackground />
        </body>
    </html>
  );
}
