import { Inter } from "next/font/google";
import "./globals.css";
import FireflyBackground from "../Components/FireflyBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Erika A Porath - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <FireflyBackground />
        </body>
    </html>
  );
}
